### ISSUE TITLE
Add logo of 'Start with a Friend'

### ISSUE THREAD

**Issue by pmaschke** [fluechtlingshilfe-babelsberg/forum#15]
Link should go to https://www.start-with-a-friend.de/standorte/potsdam/
![logo](https://user-images.githubusercontent.com/5269229/27013758-a09b2676-4eea-11e7-8b3d-6b2761774641.jpg)

**Comment by pmaschke** [comment]
If needed, other variants of the logo can be downloaded at https://www.start-with-a-friend.de/ueber-uns-1/presse/

**Comment by tom95** [comment]
Thank you for the additional info and the link!
